<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DarksFIDO2.Core\DarksFIDO2.Core.csproj" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <Resource Include="Assets\darks-fido2-logo.png" />
    <Resource Include="Assets\DarksFIDO2.ico" />
    <Content Include="Assets\favicon.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\favicon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseSystemDrawing>true</UseSystemDrawing>
    <AssemblyName>DarksFIDO2</AssemblyName>
    <ApplicationIcon>Assets\DarksFIDO2.ico</ApplicationIcon>
    <RootNamespace>DarksFIDO2.App</RootNamespace>
    <Version>0.6.1</Version>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
</Project>
